#!/bin/bash

dressage_apply_common_defaults() {
  local run_name="$1"
  local paddock_mode="${2:-blackbox}"
  local sandbox_provider="${3:-local_bwrap}"

  RUN_NAME="${RUN_NAME:-${run_name}}"
  LOG_DIR="${LOG_DIR:-${REPO_ROOT}/log}"

  PROXY_HOST="${PROXY_HOST:-0.0.0.0}"
  PROXY_PORT="${PROXY_PORT:-8800}"
  PROXY_PUBLIC_HOST="${PROXY_PUBLIC_HOST:-$(hostname -i)}"
  DRESSAGE_PROXY_URL="${DRESSAGE_PROXY_URL:-http://${PROXY_PUBLIC_HOST}:${PROXY_PORT}}"

  SGLANG_ROUTER_HOST="${SGLANG_ROUTER_HOST:-$(hostname -i)}"
  SGLANG_ROUTER_PORT="${SGLANG_ROUTER_PORT:-8000}"
  SGLANG_ROUTER_URL="${SGLANG_ROUTER_URL:-http://${SGLANG_ROUTER_HOST}:${SGLANG_ROUTER_PORT}}"

  DRESSAGE_PADDOCK_MODE="${DRESSAGE_PADDOCK_MODE:-${paddock_mode}}"
  DRESSAGE_SANDBOX_PROVIDER="${DRESSAGE_SANDBOX_PROVIDER:-${sandbox_provider}}"
  DRESSAGE_BLACKBOX_MAX_STEPS="${DRESSAGE_BLACKBOX_MAX_STEPS:-100}"
  DRESSAGE_BLACKBOX_COMPACT_THRESHOLD="${DRESSAGE_BLACKBOX_COMPACT_THRESHOLD:-}"
  if [[ "${DRESSAGE_PADDOCK_MODE}" == "whitebox" ]]; then
    DRESSAGE_LOCAL_BWRAP_POOL_MODE="${DRESSAGE_LOCAL_BWRAP_POOL_MODE:-command_only}"
  else
    DRESSAGE_LOCAL_BWRAP_POOL_MODE="${DRESSAGE_LOCAL_BWRAP_POOL_MODE:-blackbox}"
  fi

  TRAJECTORY_BUILD_MODE="${TRAJECTORY_BUILD_MODE:-concat}"
  TRAJECTORY_BUILD_MODEL="${TRAJECTORY_BUILD_MODEL:-qwen3_5}"

  DRESSAGE_TRAJECTORY_PAYLOAD_LOG_DIR="${DRESSAGE_TRAJECTORY_PAYLOAD_LOG_DIR:-${LOG_DIR}/traj_payload/${RUN_NAME}}"
  DRESSAGE_TRAJECTORY_ERROR_LOG_DIR="${DRESSAGE_TRAJECTORY_ERROR_LOG_DIR:-${LOG_DIR}/traj_err/${RUN_NAME}}"
  PROXY_LOG_FILE="${PROXY_LOG_FILE:-${LOG_DIR}/proxy/${RUN_NAME}.log}"
  PROXY_PID_FILE="${PROXY_PID_FILE:-${LOG_DIR}/proxy/${RUN_NAME}.pid}"
  mkdir -p "${LOG_DIR}" "$(dirname "${PROXY_PID_FILE}")" "${DRESSAGE_TRAJECTORY_PAYLOAD_LOG_DIR}" "${DRESSAGE_TRAJECTORY_ERROR_LOG_DIR}"
}

dressage_apply_local_bwrap_defaults() {
  local slots_per_node_default="$1"

  DRESSAGE_LOCAL_BWRAP_AUTO_START="${DRESSAGE_LOCAL_BWRAP_AUTO_START:-1}"
  DRESSAGE_LOCAL_BWRAP_RAY_NAMESPACE="${DRESSAGE_LOCAL_BWRAP_RAY_NAMESPACE:-dressage}"
  DRESSAGE_LOCAL_BWRAP_MANAGER_NAME="${DRESSAGE_LOCAL_BWRAP_MANAGER_NAME:-dressage_local_bwrap_manager}"
  DRESSAGE_LOCAL_BWRAP_BASE_PORT="${DRESSAGE_LOCAL_BWRAP_BASE_PORT:-31000}"
  DRESSAGE_BLACKBOX_ACQUIRE_TIMEOUT_SEC="${DRESSAGE_BLACKBOX_ACQUIRE_TIMEOUT_SEC:-1800}"
  DRESSAGE_BLACKBOX_SLOTS_PER_NODE="${DRESSAGE_BLACKBOX_SLOTS_PER_NODE:-${slots_per_node_default}}"
  DRESSAGE_BLACKBOX_RUNNER_MODE="${DRESSAGE_BLACKBOX_RUNNER_MODE:-bwrap}"
  DRESSAGE_BLACKBOX_BWRAP_BIN="${DRESSAGE_BLACKBOX_BWRAP_BIN:-bwrap}"
  DRESSAGE_BLACKBOX_CLEANUP_RESIDUAL_PROCESSES="${DRESSAGE_BLACKBOX_CLEANUP_RESIDUAL_PROCESSES:-1}"
  DRESSAGE_BLACKBOX_RESIDUAL_CLEANUP_TIMEOUT_SEC="${DRESSAGE_BLACKBOX_RESIDUAL_CLEANUP_TIMEOUT_SEC:-5}"
  DRESSAGE_LOCAL_BWRAP_DESTROY_ACTORS_ON_STOP="${DRESSAGE_LOCAL_BWRAP_DESTROY_ACTORS_ON_STOP:-1}"
  DRESSAGE_LOCAL_BWRAP_CLEANUP_ON_EXIT="${DRESSAGE_LOCAL_BWRAP_CLEANUP_ON_EXIT:-1}"
  DRESSAGE_RAY_STOP_ON_EXIT="${DRESSAGE_RAY_STOP_ON_EXIT:-1}"

  DRESSAGE_BLACKBOX_PRESERVE_SESSION_ARTIFACTS="${DRESSAGE_BLACKBOX_PRESERVE_SESSION_ARTIFACTS:-0}"
  DRESSAGE_BLACKBOX_SESSION_ARCHIVE_DIRS="${DRESSAGE_BLACKBOX_SESSION_ARCHIVE_DIRS:-home,work,runtime,tmp}"
  DRESSAGE_BLACKBOX_SESSION_ARCHIVE_MAX_PER_SLOT="${DRESSAGE_BLACKBOX_SESSION_ARCHIVE_MAX_PER_SLOT:-20}"
  DRESSAGE_BLACKBOX_SESSION_ARCHIVE_TTL_SEC="${DRESSAGE_BLACKBOX_SESSION_ARCHIVE_TTL_SEC:-86400}"
}

dressage_compute_local_bwrap_resources() {
  local worker_count="${1:-0}"
  DRESSAGE_LOCAL_BWRAP_TOTAL_SERVERS="${DRESSAGE_LOCAL_BWRAP_TOTAL_SERVERS:-$((DRESSAGE_BLACKBOX_SLOTS_PER_NODE + worker_count * DRESSAGE_BLACKBOX_SLOTS_PER_NODE))}"

  DRESSAGE_BLACKBOX_HEAD_RESOURCE_ARGS=()
  if [ "${DRESSAGE_BLACKBOX_SLOTS_PER_NODE}" -gt 0 ]; then
    DRESSAGE_BLACKBOX_HEAD_RESOURCE_ARGS=(--resources="{\"local_bwrap_slots\":${DRESSAGE_BLACKBOX_SLOTS_PER_NODE},\"local_bwrap_node\":1}")
  fi
  DRESSAGE_BLACKBOX_WORKER_RESOURCE_ARGS=""
  if [ "${DRESSAGE_BLACKBOX_SLOTS_PER_NODE}" -gt 0 ]; then
    DRESSAGE_BLACKBOX_WORKER_RESOURCE_ARGS="--resources='{\"local_bwrap_slots\":${DRESSAGE_BLACKBOX_SLOTS_PER_NODE},\"local_bwrap_node\":1}'"
  fi
  DRESSAGE_LOCAL_BWRAP_HEAD_RESOURCE_ARGS=("${DRESSAGE_BLACKBOX_HEAD_RESOURCE_ARGS[@]}")
  DRESSAGE_LOCAL_BWRAP_WORKER_RESOURCE_ARGS="${DRESSAGE_BLACKBOX_WORKER_RESOURCE_ARGS}"
}

dressage_validate_proxy_defaults() {
  if [[ "${DRESSAGE_PROXY_URL}" =~ ^https?://(localhost|127\.|0\.0\.0\.0|\[::1\]|::1)([:/]|$) ]]; then
    echo "DRESSAGE_PROXY_URL must be reachable from the sandbox; got local-only URL: ${DRESSAGE_PROXY_URL}" >&2
    echo "Set PROXY_PUBLIC_HOST or DRESSAGE_PROXY_URL to this machine's sandbox-reachable IP/hostname." >&2
    exit 1
  fi
  if [[ "${SGLANG_ROUTER_URL}" =~ ^https?://(0\.0\.0\.0|\[::\]|::)([:/]|$) ]]; then
    echo "SGLANG_ROUTER_URL is a proxy client target and cannot use a wildcard bind address: ${SGLANG_ROUTER_URL}" >&2
    echo "Set SGLANG_ROUTER_HOST or SGLANG_ROUTER_URL to a reachable host, e.g. ${PROXY_PUBLIC_HOST}." >&2
    exit 1
  fi
}

dressage_compute_context_window() {
  local default_max_tokens_per_gpu="$1"
  local cp_size="${2:-${CP_SIZE:-1}}"

  MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-${default_max_tokens_per_gpu}}"
  CONTEXT_WINDOW="${CONTEXT_WINDOW:-$((MAX_TOKENS_PER_GPU * cp_size))}"
  export MAX_TOKENS_PER_GPU CONTEXT_WINDOW
}

dressage_clear_trajectory_logs() {
  for TRAJECTORY_LOG_DIR_VAR in DRESSAGE_TRAJECTORY_PAYLOAD_LOG_DIR DRESSAGE_TRAJECTORY_ERROR_LOG_DIR; do
    TRAJECTORY_LOG_DIR="${!TRAJECTORY_LOG_DIR_VAR}"
    if [[ -z "${TRAJECTORY_LOG_DIR}" || "${TRAJECTORY_LOG_DIR}" == "/" ]]; then
      echo "Refusing to clear unsafe ${TRAJECTORY_LOG_DIR_VAR}: ${TRAJECTORY_LOG_DIR}" >&2
      exit 1
    fi
    echo "Clearing ${TRAJECTORY_LOG_DIR_VAR}: ${TRAJECTORY_LOG_DIR}"
    find "${TRAJECTORY_LOG_DIR}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  done
}

dressage_export_common_env() {
  export RUN_NAME LOG_DIR
  export SGLANG_ROUTER_URL
  export DRESSAGE_PROXY_URL
  export DRESSAGE_PADDOCK_MODE DRESSAGE_SANDBOX_PROVIDER
  export DRESSAGE_BLACKBOX_MAX_STEPS DRESSAGE_BLACKBOX_COMPACT_THRESHOLD
  export DRESSAGE_TRAJECTORY_PAYLOAD_LOG_DIR DRESSAGE_TRAJECTORY_ERROR_LOG_DIR
  export DRESSAGE_RUN_NAME="${RUN_NAME}"
}

dressage_export_local_bwrap_env() {
  export DRESSAGE_LOCAL_BWRAP_AUTO_START DRESSAGE_LOCAL_BWRAP_POOL_MODE
  export DRESSAGE_LOCAL_BWRAP_RAY_NAMESPACE DRESSAGE_LOCAL_BWRAP_MANAGER_NAME
  export DRESSAGE_LOCAL_BWRAP_TOTAL_SERVERS DRESSAGE_LOCAL_BWRAP_BASE_PORT
  export DRESSAGE_BLACKBOX_ACQUIRE_TIMEOUT_SEC DRESSAGE_BLACKBOX_SLOTS_PER_NODE
  export DRESSAGE_BLACKBOX_RUNNER_MODE DRESSAGE_BLACKBOX_BWRAP_BIN
  export DRESSAGE_BLACKBOX_CLEANUP_RESIDUAL_PROCESSES DRESSAGE_BLACKBOX_RESIDUAL_CLEANUP_TIMEOUT_SEC
  export DRESSAGE_LOCAL_BWRAP_DESTROY_ACTORS_ON_STOP DRESSAGE_LOCAL_BWRAP_CLEANUP_ON_EXIT DRESSAGE_RAY_STOP_ON_EXIT
  export DRESSAGE_BLACKBOX_PRESERVE_SESSION_ARTIFACTS DRESSAGE_BLACKBOX_SESSION_ARCHIVE_DIRS
  export DRESSAGE_BLACKBOX_SESSION_ARCHIVE_MAX_PER_SLOT DRESSAGE_BLACKBOX_SESSION_ARCHIVE_TTL_SEC
}
